sudo: required
dist: trusty
language: c++
compiler:
  - gcc
  - clang
notifications:
  email: false
env:
  global:
    - ROS_REPO=ros
    - CXXFLAGS="-Werror=uninitialized -Werror=return-type -Werror=format"
    - ADDITIONAL_DEBS=clang
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
#  - ./travis.sh  # Enable this when you have a package-local script
